apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discord-bot
resources:
  - ../../base
configMapGenerator:
  - name: discord-bot-config
    options:
      disableNameSuffixHash: true
    literals:
      - "DB_POSTGRES_HOST=postgres"
      - "DB_POSTGRES_PORT=5432"
      - "LAVALINK_MAIN_NODE_HOST=lavalink"
      - "LAVALINK_MAIN_NODE_PORT=2333"
    envs:
      - config.env
secretGenerator:
  - name: discord-bot-secret
    options:
      disableNameSuffixHash: true
    envs:
      - secrets.env
