// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package autorolemock

import (
	"context"

	"github.com/SkinonikS/discord-bot-go/internal/service/repository/auto_role"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRepo
func (_mock *MockRepo) Delete(ctx context.Context, params autorole.DeleteParams) (int64, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, autorole.DeleteParams) (int64, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, autorole.DeleteParams) int64); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, autorole.DeleteParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - params autorole.DeleteParams
func (_e *MockRepo_Expecter) Delete(ctx any, params any) *MockRepo_Delete_Call {
	return &MockRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, params)}
}

func (_c *MockRepo_Delete_Call) Run(run func(ctx context.Context, params autorole.DeleteParams)) *MockRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 autorole.DeleteParams
		if args[1] != nil {
			arg1 = args[1].(autorole.DeleteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Delete_Call) Return(n int64, err error) *MockRepo_Delete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, params autorole.DeleteParams) (int64, error)) *MockRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockRepo
func (_mock *MockRepo) Find(ctx context.Context, params autorole.FindParams) ([]autorole.AutoRole, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []autorole.AutoRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, autorole.FindParams) ([]autorole.AutoRole, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, autorole.FindParams) []autorole.AutoRole); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]autorole.AutoRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, autorole.FindParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRepo_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - params autorole.FindParams
func (_e *MockRepo_Expecter) Find(ctx any, params any) *MockRepo_Find_Call {
	return &MockRepo_Find_Call{Call: _e.mock.On("Find", ctx, params)}
}

func (_c *MockRepo_Find_Call) Run(run func(ctx context.Context, params autorole.FindParams)) *MockRepo_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 autorole.FindParams
		if args[1] != nil {
			arg1 = args[1].(autorole.FindParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Find_Call) Return(autoRoles []autorole.AutoRole, err error) *MockRepo_Find_Call {
	_c.Call.Return(autoRoles, err)
	return _c
}

func (_c *MockRepo_Find_Call) RunAndReturn(run func(ctx context.Context, params autorole.FindParams) ([]autorole.AutoRole, error)) *MockRepo_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepo
func (_mock *MockRepo) Save(ctx context.Context, autoRole *autorole.AutoRole) error {
	ret := _mock.Called(ctx, autoRole)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *autorole.AutoRole) error); ok {
		r0 = returnFunc(ctx, autoRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - autoRole *autorole.AutoRole
func (_e *MockRepo_Expecter) Save(ctx any, autoRole any) *MockRepo_Save_Call {
	return &MockRepo_Save_Call{Call: _e.mock.On("Save", ctx, autoRole)}
}

func (_c *MockRepo_Save_Call) Run(run func(ctx context.Context, autoRole *autorole.AutoRole)) *MockRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *autorole.AutoRole
		if args[1] != nil {
			arg1 = args[1].(*autorole.AutoRole)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Save_Call) Return(err error) *MockRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Save_Call) RunAndReturn(run func(ctx context.Context, autoRole *autorole.AutoRole) error) *MockRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
