// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package autorolemock

import (
	"context"

	"github.com/SkinonikS/discord-bot-go/internal/service/repository/auto_role"
	"github.com/disgoorg/snowflake/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// DeleteByGuildIDAndRoleID provides a mock function for the type MockRepo
func (_mock *MockRepo) DeleteByGuildIDAndRoleID(ctx context.Context, guildID snowflake.ID, roleID snowflake.ID) (int64, error) {
	ret := _mock.Called(ctx, guildID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByGuildIDAndRoleID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID, snowflake.ID) (int64, error)); ok {
		return returnFunc(ctx, guildID, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID, snowflake.ID) int64); ok {
		r0 = returnFunc(ctx, guildID, roleID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snowflake.ID, snowflake.ID) error); ok {
		r1 = returnFunc(ctx, guildID, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_DeleteByGuildIDAndRoleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByGuildIDAndRoleID'
type MockRepo_DeleteByGuildIDAndRoleID_Call struct {
	*mock.Call
}

// DeleteByGuildIDAndRoleID is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID snowflake.ID
//   - roleID snowflake.ID
func (_e *MockRepo_Expecter) DeleteByGuildIDAndRoleID(ctx any, guildID any, roleID any) *MockRepo_DeleteByGuildIDAndRoleID_Call {
	return &MockRepo_DeleteByGuildIDAndRoleID_Call{Call: _e.mock.On("DeleteByGuildIDAndRoleID", ctx, guildID, roleID)}
}

func (_c *MockRepo_DeleteByGuildIDAndRoleID_Call) Run(run func(ctx context.Context, guildID snowflake.ID, roleID snowflake.ID)) *MockRepo_DeleteByGuildIDAndRoleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(snowflake.ID)
		}
		var arg2 snowflake.ID
		if args[2] != nil {
			arg2 = args[2].(snowflake.ID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_DeleteByGuildIDAndRoleID_Call) Return(n int64, err error) *MockRepo_DeleteByGuildIDAndRoleID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepo_DeleteByGuildIDAndRoleID_Call) RunAndReturn(run func(ctx context.Context, guildID snowflake.ID, roleID snowflake.ID) (int64, error)) *MockRepo_DeleteByGuildIDAndRoleID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByGuildID provides a mock function for the type MockRepo
func (_mock *MockRepo) FindByGuildID(ctx context.Context, guildID snowflake.ID) ([]autorole.AutoRole, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for FindByGuildID")
	}

	var r0 []autorole.AutoRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID) ([]autorole.AutoRole, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID) []autorole.AutoRole); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]autorole.AutoRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snowflake.ID) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_FindByGuildID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGuildID'
type MockRepo_FindByGuildID_Call struct {
	*mock.Call
}

// FindByGuildID is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID snowflake.ID
func (_e *MockRepo_Expecter) FindByGuildID(ctx any, guildID any) *MockRepo_FindByGuildID_Call {
	return &MockRepo_FindByGuildID_Call{Call: _e.mock.On("FindByGuildID", ctx, guildID)}
}

func (_c *MockRepo_FindByGuildID_Call) Run(run func(ctx context.Context, guildID snowflake.ID)) *MockRepo_FindByGuildID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(snowflake.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_FindByGuildID_Call) Return(autoRoles []autorole.AutoRole, err error) *MockRepo_FindByGuildID_Call {
	_c.Call.Return(autoRoles, err)
	return _c
}

func (_c *MockRepo_FindByGuildID_Call) RunAndReturn(run func(ctx context.Context, guildID snowflake.ID) ([]autorole.AutoRole, error)) *MockRepo_FindByGuildID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepo
func (_mock *MockRepo) Save(ctx context.Context, autoRole *autorole.AutoRole) error {
	ret := _mock.Called(ctx, autoRole)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *autorole.AutoRole) error); ok {
		r0 = returnFunc(ctx, autoRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - autoRole *autorole.AutoRole
func (_e *MockRepo_Expecter) Save(ctx any, autoRole any) *MockRepo_Save_Call {
	return &MockRepo_Save_Call{Call: _e.mock.On("Save", ctx, autoRole)}
}

func (_c *MockRepo_Save_Call) Run(run func(ctx context.Context, autoRole *autorole.AutoRole)) *MockRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *autorole.AutoRole
		if args[1] != nil {
			arg1 = args[1].(*autorole.AutoRole)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Save_Call) Return(err error) *MockRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Save_Call) RunAndReturn(run func(ctx context.Context, autoRole *autorole.AutoRole) error) *MockRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}
