apiVersion: v1
kind: Service
metadata:
  name: pg-view
  namespace: discord-bot
spec:
  selector:
    app: pg-view
  ports:
    - port: 3000
      targetPort: http
      nodePort: 30300
  type: NodePort
