apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432; do
                echo waiting for postgres
                sleep 2
              done
        - name: wait-for-lavalink
          image: busybox:1.37
          env:
            - name: LAVALINK_MAIN_NODE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: LAVALINK_MAIN_NODE_PASSWORD
          command:
            - sh
            - -c
            - |
              until wget -qO- --header="Authorization: $LAVALINK_MAIN_NODE_PASSWORD" http://lavalink:2333/version; do
                echo waiting for lavalink
                sleep 2
              done
      containers:
        - name: discord-bot
          image: ghcr.io/skinoniks/discord-bot:latest
          imagePullPolicy: Always
          env:
            - name: APP_ROOT_DIR
              value: /app
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: APP_ENV
            - name: APP_DEBUG
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: APP_DEBUG
            - name: APP_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: APP_REPOSITORY
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: LOG_LEVEL
            - name: LAVALINK_MAIN_NODE_HOST
              value: "lavalink"
            - name: LAVALINK_MAIN_NODE_PORT
              value: "2333"
            - name: LAVALINK_MAIN_NODE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: LAVALINK_MAIN_NODE_PASSWORD
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_TOKEN
            - name: DISCORD_APP_ID
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_APP_ID
            - name: DB_POSTGRES_HOST
              value: "postgres"
            - name: DB_POSTGRES_PORT
              value: "5432"
            - name: DB_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DB_POSTGRES_USER
            - name: DB_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DB_POSTGRES_PASSWORD
            - name: DB_POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DB_POSTGRES_DB
            - name: DB_POSTGRES_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DB_POSTGRES_SSLMODE
            - name: HTTP_SERVER_ADDR
              value: ":8081"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: storage
              mountPath: /app/storage
          readinessProbe:
            httpGet:
              port: 8081
              path: "/readyz"
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8081
              path: "/livez"
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: discord-bot-storage
