// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package musicplayermock

import (
	"context"

	"github.com/disgoorg/disgolink/v3/disgolink"
	"github.com/disgoorg/disgolink/v3/lavalink"
	"github.com/disgoorg/snowflake/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayer creates a new instance of MockPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPlayer is an autogenerated mock type for the Player type
type MockPlayer struct {
	mock.Mock
}

type MockPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayer) EXPECT() *MockPlayer_Expecter {
	return &MockPlayer_Expecter{mock: &_m.Mock}
}

// ChannelID provides a mock function for the type MockPlayer
func (_mock *MockPlayer) ChannelID() *snowflake.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChannelID")
	}

	var r0 *snowflake.ID
	if returnFunc, ok := ret.Get(0).(func() *snowflake.ID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*snowflake.ID)
		}
	}
	return r0
}

// MockPlayer_ChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChannelID'
type MockPlayer_ChannelID_Call struct {
	*mock.Call
}

// ChannelID is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) ChannelID() *MockPlayer_ChannelID_Call {
	return &MockPlayer_ChannelID_Call{Call: _e.mock.On("ChannelID")}
}

func (_c *MockPlayer_ChannelID_Call) Run(run func()) *MockPlayer_ChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_ChannelID_Call) Return(iD *snowflake.ID) *MockPlayer_ChannelID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockPlayer_ChannelID_Call) RunAndReturn(run func() *snowflake.ID) *MockPlayer_ChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Destroy(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockPlayer_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPlayer_Expecter) Destroy(ctx any) *MockPlayer_Destroy_Call {
	return &MockPlayer_Destroy_Call{Call: _e.mock.On("Destroy", ctx)}
}

func (_c *MockPlayer_Destroy_Call) Run(run func(ctx context.Context)) *MockPlayer_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayer_Destroy_Call) Return(err error) *MockPlayer_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Destroy_Call) RunAndReturn(run func(ctx context.Context) error) *MockPlayer_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Filters provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Filters() lavalink.Filters {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Filters")
	}

	var r0 lavalink.Filters
	if returnFunc, ok := ret.Get(0).(func() lavalink.Filters); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(lavalink.Filters)
	}
	return r0
}

// MockPlayer_Filters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filters'
type MockPlayer_Filters_Call struct {
	*mock.Call
}

// Filters is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Filters() *MockPlayer_Filters_Call {
	return &MockPlayer_Filters_Call{Call: _e.mock.On("Filters")}
}

func (_c *MockPlayer_Filters_Call) Run(run func()) *MockPlayer_Filters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Filters_Call) Return(filters lavalink.Filters) *MockPlayer_Filters_Call {
	_c.Call.Return(filters)
	return _c
}

func (_c *MockPlayer_Filters_Call) RunAndReturn(run func() lavalink.Filters) *MockPlayer_Filters_Call {
	_c.Call.Return(run)
	return _c
}

// GuildID provides a mock function for the type MockPlayer
func (_mock *MockPlayer) GuildID() snowflake.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GuildID")
	}

	var r0 snowflake.ID
	if returnFunc, ok := ret.Get(0).(func() snowflake.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(snowflake.ID)
	}
	return r0
}

// MockPlayer_GuildID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuildID'
type MockPlayer_GuildID_Call struct {
	*mock.Call
}

// GuildID is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) GuildID() *MockPlayer_GuildID_Call {
	return &MockPlayer_GuildID_Call{Call: _e.mock.On("GuildID")}
}

func (_c *MockPlayer_GuildID_Call) Run(run func()) *MockPlayer_GuildID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_GuildID_Call) Return(iD snowflake.ID) *MockPlayer_GuildID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockPlayer_GuildID_Call) RunAndReturn(run func() snowflake.ID) *MockPlayer_GuildID_Call {
	_c.Call.Return(run)
	return _c
}

// Lavalink provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Lavalink() disgolink.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lavalink")
	}

	var r0 disgolink.Client
	if returnFunc, ok := ret.Get(0).(func() disgolink.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(disgolink.Client)
		}
	}
	return r0
}

// MockPlayer_Lavalink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lavalink'
type MockPlayer_Lavalink_Call struct {
	*mock.Call
}

// Lavalink is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Lavalink() *MockPlayer_Lavalink_Call {
	return &MockPlayer_Lavalink_Call{Call: _e.mock.On("Lavalink")}
}

func (_c *MockPlayer_Lavalink_Call) Run(run func()) *MockPlayer_Lavalink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Lavalink_Call) Return(client disgolink.Client) *MockPlayer_Lavalink_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockPlayer_Lavalink_Call) RunAndReturn(run func() disgolink.Client) *MockPlayer_Lavalink_Call {
	_c.Call.Return(run)
	return _c
}

// Node provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Node() disgolink.Node {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Node")
	}

	var r0 disgolink.Node
	if returnFunc, ok := ret.Get(0).(func() disgolink.Node); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(disgolink.Node)
		}
	}
	return r0
}

// MockPlayer_Node_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Node'
type MockPlayer_Node_Call struct {
	*mock.Call
}

// Node is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Node() *MockPlayer_Node_Call {
	return &MockPlayer_Node_Call{Call: _e.mock.On("Node")}
}

func (_c *MockPlayer_Node_Call) Run(run func()) *MockPlayer_Node_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Node_Call) Return(node disgolink.Node) *MockPlayer_Node_Call {
	_c.Call.Return(node)
	return _c
}

func (_c *MockPlayer_Node_Call) RunAndReturn(run func() disgolink.Node) *MockPlayer_Node_Call {
	_c.Call.Return(run)
	return _c
}

// OnEvent provides a mock function for the type MockPlayer
func (_mock *MockPlayer) OnEvent(event lavalink.Event) {
	_mock.Called(event)
	return
}

// MockPlayer_OnEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnEvent'
type MockPlayer_OnEvent_Call struct {
	*mock.Call
}

// OnEvent is a helper method to define mock.On call
//   - event lavalink.Event
func (_e *MockPlayer_Expecter) OnEvent(event any) *MockPlayer_OnEvent_Call {
	return &MockPlayer_OnEvent_Call{Call: _e.mock.On("OnEvent", event)}
}

func (_c *MockPlayer_OnEvent_Call) Run(run func(event lavalink.Event)) *MockPlayer_OnEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lavalink.Event
		if args[0] != nil {
			arg0 = args[0].(lavalink.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayer_OnEvent_Call) Return() *MockPlayer_OnEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_OnEvent_Call) RunAndReturn(run func(event lavalink.Event)) *MockPlayer_OnEvent_Call {
	_c.Run(run)
	return _c
}

// OnPlayerUpdate provides a mock function for the type MockPlayer
func (_mock *MockPlayer) OnPlayerUpdate(state lavalink.PlayerState) {
	_mock.Called(state)
	return
}

// MockPlayer_OnPlayerUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPlayerUpdate'
type MockPlayer_OnPlayerUpdate_Call struct {
	*mock.Call
}

// OnPlayerUpdate is a helper method to define mock.On call
//   - state lavalink.PlayerState
func (_e *MockPlayer_Expecter) OnPlayerUpdate(state any) *MockPlayer_OnPlayerUpdate_Call {
	return &MockPlayer_OnPlayerUpdate_Call{Call: _e.mock.On("OnPlayerUpdate", state)}
}

func (_c *MockPlayer_OnPlayerUpdate_Call) Run(run func(state lavalink.PlayerState)) *MockPlayer_OnPlayerUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lavalink.PlayerState
		if args[0] != nil {
			arg0 = args[0].(lavalink.PlayerState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayer_OnPlayerUpdate_Call) Return() *MockPlayer_OnPlayerUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_OnPlayerUpdate_Call) RunAndReturn(run func(state lavalink.PlayerState)) *MockPlayer_OnPlayerUpdate_Call {
	_c.Run(run)
	return _c
}

// OnVoiceServerUpdate provides a mock function for the type MockPlayer
func (_mock *MockPlayer) OnVoiceServerUpdate(ctx context.Context, token string, endpoint string) {
	_mock.Called(ctx, token, endpoint)
	return
}

// MockPlayer_OnVoiceServerUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnVoiceServerUpdate'
type MockPlayer_OnVoiceServerUpdate_Call struct {
	*mock.Call
}

// OnVoiceServerUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - endpoint string
func (_e *MockPlayer_Expecter) OnVoiceServerUpdate(ctx any, token any, endpoint any) *MockPlayer_OnVoiceServerUpdate_Call {
	return &MockPlayer_OnVoiceServerUpdate_Call{Call: _e.mock.On("OnVoiceServerUpdate", ctx, token, endpoint)}
}

func (_c *MockPlayer_OnVoiceServerUpdate_Call) Run(run func(ctx context.Context, token string, endpoint string)) *MockPlayer_OnVoiceServerUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlayer_OnVoiceServerUpdate_Call) Return() *MockPlayer_OnVoiceServerUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_OnVoiceServerUpdate_Call) RunAndReturn(run func(ctx context.Context, token string, endpoint string)) *MockPlayer_OnVoiceServerUpdate_Call {
	_c.Run(run)
	return _c
}

// OnVoiceStateUpdate provides a mock function for the type MockPlayer
func (_mock *MockPlayer) OnVoiceStateUpdate(ctx context.Context, channelID *snowflake.ID, sessionID string) {
	_mock.Called(ctx, channelID, sessionID)
	return
}

// MockPlayer_OnVoiceStateUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnVoiceStateUpdate'
type MockPlayer_OnVoiceStateUpdate_Call struct {
	*mock.Call
}

// OnVoiceStateUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID *snowflake.ID
//   - sessionID string
func (_e *MockPlayer_Expecter) OnVoiceStateUpdate(ctx any, channelID any, sessionID any) *MockPlayer_OnVoiceStateUpdate_Call {
	return &MockPlayer_OnVoiceStateUpdate_Call{Call: _e.mock.On("OnVoiceStateUpdate", ctx, channelID, sessionID)}
}

func (_c *MockPlayer_OnVoiceStateUpdate_Call) Run(run func(ctx context.Context, channelID *snowflake.ID, sessionID string)) *MockPlayer_OnVoiceStateUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(*snowflake.ID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlayer_OnVoiceStateUpdate_Call) Return() *MockPlayer_OnVoiceStateUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_OnVoiceStateUpdate_Call) RunAndReturn(run func(ctx context.Context, channelID *snowflake.ID, sessionID string)) *MockPlayer_OnVoiceStateUpdate_Call {
	_c.Run(run)
	return _c
}

// Paused provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Paused() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Paused")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPlayer_Paused_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Paused'
type MockPlayer_Paused_Call struct {
	*mock.Call
}

// Paused is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Paused() *MockPlayer_Paused_Call {
	return &MockPlayer_Paused_Call{Call: _e.mock.On("Paused")}
}

func (_c *MockPlayer_Paused_Call) Run(run func()) *MockPlayer_Paused_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Paused_Call) Return(b bool) *MockPlayer_Paused_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPlayer_Paused_Call) RunAndReturn(run func() bool) *MockPlayer_Paused_Call {
	_c.Call.Return(run)
	return _c
}

// Position provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Position() lavalink.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Position")
	}

	var r0 lavalink.Duration
	if returnFunc, ok := ret.Get(0).(func() lavalink.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(lavalink.Duration)
	}
	return r0
}

// MockPlayer_Position_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Position'
type MockPlayer_Position_Call struct {
	*mock.Call
}

// Position is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Position() *MockPlayer_Position_Call {
	return &MockPlayer_Position_Call{Call: _e.mock.On("Position")}
}

func (_c *MockPlayer_Position_Call) Run(run func()) *MockPlayer_Position_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Position_Call) Return(duration lavalink.Duration) *MockPlayer_Position_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockPlayer_Position_Call) RunAndReturn(run func() lavalink.Duration) *MockPlayer_Position_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Restore(player lavalink.Player) {
	_mock.Called(player)
	return
}

// MockPlayer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockPlayer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - player lavalink.Player
func (_e *MockPlayer_Expecter) Restore(player any) *MockPlayer_Restore_Call {
	return &MockPlayer_Restore_Call{Call: _e.mock.On("Restore", player)}
}

func (_c *MockPlayer_Restore_Call) Run(run func(player lavalink.Player)) *MockPlayer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lavalink.Player
		if args[0] != nil {
			arg0 = args[0].(lavalink.Player)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayer_Restore_Call) Return() *MockPlayer_Restore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPlayer_Restore_Call) RunAndReturn(run func(player lavalink.Player)) *MockPlayer_Restore_Call {
	_c.Run(run)
	return _c
}

// State provides a mock function for the type MockPlayer
func (_mock *MockPlayer) State() lavalink.PlayerState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 lavalink.PlayerState
	if returnFunc, ok := ret.Get(0).(func() lavalink.PlayerState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(lavalink.PlayerState)
	}
	return r0
}

// MockPlayer_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockPlayer_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) State() *MockPlayer_State_Call {
	return &MockPlayer_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockPlayer_State_Call) Run(run func()) *MockPlayer_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_State_Call) Return(playerState lavalink.PlayerState) *MockPlayer_State_Call {
	_c.Call.Return(playerState)
	return _c
}

func (_c *MockPlayer_State_Call) RunAndReturn(run func() lavalink.PlayerState) *MockPlayer_State_Call {
	_c.Call.Return(run)
	return _c
}

// Track provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Track() *lavalink.Track {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 *lavalink.Track
	if returnFunc, ok := ret.Get(0).(func() *lavalink.Track); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lavalink.Track)
		}
	}
	return r0
}

// MockPlayer_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockPlayer_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Track() *MockPlayer_Track_Call {
	return &MockPlayer_Track_Call{Call: _e.mock.On("Track")}
}

func (_c *MockPlayer_Track_Call) Run(run func()) *MockPlayer_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Track_Call) Return(track *lavalink.Track) *MockPlayer_Track_Call {
	_c.Call.Return(track)
	return _c
}

func (_c *MockPlayer_Track_Call) RunAndReturn(run func() *lavalink.Track) *MockPlayer_Track_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Update(ctx context.Context, opts ...lavalink.PlayerUpdateOpt) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...lavalink.PlayerUpdateOpt) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlayer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlayer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...lavalink.PlayerUpdateOpt
func (_e *MockPlayer_Expecter) Update(ctx any, opts ...any) *MockPlayer_Update_Call {
	return &MockPlayer_Update_Call{Call: _e.mock.On("Update",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockPlayer_Update_Call) Run(run func(ctx context.Context, opts ...lavalink.PlayerUpdateOpt)) *MockPlayer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []lavalink.PlayerUpdateOpt
		var variadicArgs []lavalink.PlayerUpdateOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]lavalink.PlayerUpdateOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockPlayer_Update_Call) Return(err error) *MockPlayer_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlayer_Update_Call) RunAndReturn(run func(ctx context.Context, opts ...lavalink.PlayerUpdateOpt) error) *MockPlayer_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Volume provides a mock function for the type MockPlayer
func (_mock *MockPlayer) Volume() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Volume")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPlayer_Volume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Volume'
type MockPlayer_Volume_Call struct {
	*mock.Call
}

// Volume is a helper method to define mock.On call
func (_e *MockPlayer_Expecter) Volume() *MockPlayer_Volume_Call {
	return &MockPlayer_Volume_Call{Call: _e.mock.On("Volume")}
}

func (_c *MockPlayer_Volume_Call) Run(run func()) *MockPlayer_Volume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlayer_Volume_Call) Return(n int) *MockPlayer_Volume_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPlayer_Volume_Call) RunAndReturn(run func() int) *MockPlayer_Volume_Call {
	_c.Call.Return(run)
	return _c
}
