// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package musicplayermock

import (
	"time"

	"github.com/SkinonikS/discord-bot-go/internal/service/music_player"
	"github.com/disgoorg/snowflake/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// StartTimer provides a mock function for the type MockService
func (_mock *MockService) StartTimer(st musicplayer.StartTimer) *time.Timer {
	ret := _mock.Called(st)

	if len(ret) == 0 {
		panic("no return value specified for StartTimer")
	}

	var r0 *time.Timer
	if returnFunc, ok := ret.Get(0).(func(musicplayer.StartTimer) *time.Timer); ok {
		r0 = returnFunc(st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Timer)
		}
	}
	return r0
}

// MockService_StartTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTimer'
type MockService_StartTimer_Call struct {
	*mock.Call
}

// StartTimer is a helper method to define mock.On call
//   - st musicplayer.StartTimer
func (_e *MockService_Expecter) StartTimer(st any) *MockService_StartTimer_Call {
	return &MockService_StartTimer_Call{Call: _e.mock.On("StartTimer", st)}
}

func (_c *MockService_StartTimer_Call) Run(run func(st musicplayer.StartTimer)) *MockService_StartTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 musicplayer.StartTimer
		if args[0] != nil {
			arg0 = args[0].(musicplayer.StartTimer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_StartTimer_Call) Return(timer *time.Timer) *MockService_StartTimer_Call {
	_c.Call.Return(timer)
	return _c
}

func (_c *MockService_StartTimer_Call) RunAndReturn(run func(st musicplayer.StartTimer) *time.Timer) *MockService_StartTimer_Call {
	_c.Call.Return(run)
	return _c
}

// StopTimer provides a mock function for the type MockService
func (_mock *MockService) StopTimer(guildID snowflake.ID) bool {
	ret := _mock.Called(guildID)

	if len(ret) == 0 {
		panic("no return value specified for StopTimer")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(snowflake.ID) bool); ok {
		r0 = returnFunc(guildID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_StopTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTimer'
type MockService_StopTimer_Call struct {
	*mock.Call
}

// StopTimer is a helper method to define mock.On call
//   - guildID snowflake.ID
func (_e *MockService_Expecter) StopTimer(guildID any) *MockService_StopTimer_Call {
	return &MockService_StopTimer_Call{Call: _e.mock.On("StopTimer", guildID)}
}

func (_c *MockService_StopTimer_Call) Run(run func(guildID snowflake.ID)) *MockService_StopTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 snowflake.ID
		if args[0] != nil {
			arg0 = args[0].(snowflake.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_StopTimer_Call) Return(b bool) *MockService_StopTimer_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_StopTimer_Call) RunAndReturn(run func(guildID snowflake.ID) bool) *MockService_StopTimer_Call {
	_c.Call.Return(run)
	return _c
}
