// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reactionrolemock

import (
	"context"
	"uuid"

	"github.com/SkinonikS/discord-bot-go/internal/service/repository/reaction_role"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// DeleteManyByIDs provides a mock function for the type MockRepo
func (_mock *MockRepo) DeleteManyByIDs(ctx context.Context, ids []uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManyByIDs")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_DeleteManyByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManyByIDs'
type MockRepo_DeleteManyByIDs_Call struct {
	*mock.Call
}

// DeleteManyByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockRepo_Expecter) DeleteManyByIDs(ctx any, ids any) *MockRepo_DeleteManyByIDs_Call {
	return &MockRepo_DeleteManyByIDs_Call{Call: _e.mock.On("DeleteManyByIDs", ctx, ids)}
}

func (_c *MockRepo_DeleteManyByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockRepo_DeleteManyByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_DeleteManyByIDs_Call) Return(n int64, err error) *MockRepo_DeleteManyByIDs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepo_DeleteManyByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (int64, error)) *MockRepo_DeleteManyByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCriteria provides a mock function for the type MockRepo
func (_mock *MockRepo) FindByCriteria(ctx context.Context, criteria reactionrole.SearchCriteria) ([]reactionrole.ReactionRole, error) {
	ret := _mock.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for FindByCriteria")
	}

	var r0 []reactionrole.ReactionRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, reactionrole.SearchCriteria) ([]reactionrole.ReactionRole, error)); ok {
		return returnFunc(ctx, criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, reactionrole.SearchCriteria) []reactionrole.ReactionRole); ok {
		r0 = returnFunc(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reactionrole.ReactionRole)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, reactionrole.SearchCriteria) error); ok {
		r1 = returnFunc(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_FindByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCriteria'
type MockRepo_FindByCriteria_Call struct {
	*mock.Call
}

// FindByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria reactionrole.SearchCriteria
func (_e *MockRepo_Expecter) FindByCriteria(ctx any, criteria any) *MockRepo_FindByCriteria_Call {
	return &MockRepo_FindByCriteria_Call{Call: _e.mock.On("FindByCriteria", ctx, criteria)}
}

func (_c *MockRepo_FindByCriteria_Call) Run(run func(ctx context.Context, criteria reactionrole.SearchCriteria)) *MockRepo_FindByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 reactionrole.SearchCriteria
		if args[1] != nil {
			arg1 = args[1].(reactionrole.SearchCriteria)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_FindByCriteria_Call) Return(reactionRoles []reactionrole.ReactionRole, err error) *MockRepo_FindByCriteria_Call {
	_c.Call.Return(reactionRoles, err)
	return _c
}

func (_c *MockRepo_FindByCriteria_Call) RunAndReturn(run func(ctx context.Context, criteria reactionrole.SearchCriteria) ([]reactionrole.ReactionRole, error)) *MockRepo_FindByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepo
func (_mock *MockRepo) Save(ctx context.Context, reactionRole *reactionrole.ReactionRole) error {
	ret := _mock.Called(ctx, reactionRole)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *reactionrole.ReactionRole) error); ok {
		r0 = returnFunc(ctx, reactionRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - reactionRole *reactionrole.ReactionRole
func (_e *MockRepo_Expecter) Save(ctx any, reactionRole any) *MockRepo_Save_Call {
	return &MockRepo_Save_Call{Call: _e.mock.On("Save", ctx, reactionRole)}
}

func (_c *MockRepo_Save_Call) Run(run func(ctx context.Context, reactionRole *reactionrole.ReactionRole)) *MockRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *reactionrole.ReactionRole
		if args[1] != nil {
			arg1 = args[1].(*reactionrole.ReactionRole)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Save_Call) Return(err error) *MockRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Save_Call) RunAndReturn(run func(ctx context.Context, reactionRole *reactionrole.ReactionRole) error) *MockRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type MockRepo
func (_mock *MockRepo) Transaction(ctx context.Context, fn func(tx reactionrole.Repo) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx reactionrole.Repo) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepo_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx reactionrole.Repo) error
func (_e *MockRepo_Expecter) Transaction(ctx any, fn any) *MockRepo_Transaction_Call {
	return &MockRepo_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockRepo_Transaction_Call) Run(run func(ctx context.Context, fn func(tx reactionrole.Repo) error)) *MockRepo_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx reactionrole.Repo) error
		if args[1] != nil {
			arg1 = args[1].(func(tx reactionrole.Repo) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Transaction_Call) Return(err error) *MockRepo_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx reactionrole.Repo) error) error) *MockRepo_Transaction_Call {
	_c.Call.Return(run)
	return _c
}
