database:
  host: "${DB_POSTGRES_HOST:localhost}"
  port: "${DB_POSTGRES_PORT:5432}"
  user: "${DB_POSTGRES_USER:discord_bot}"
  password: "${DB_POSTGRES_PASSWORD:root}"
  db: "${DB_POSTGRES_DB:discord_bot}"
  ssl_mode: "${DB_POSTGRES_SSLMODE:disable}"
app:
  name: "${APP_NAME:discord-bot}"
  debug: ${APP_DEBUG:false}
  repository: "${APP_REPOSITORY:''}"
http_server:
  addr: "${HTTP_SERVER_ADDR:':8081'}"
logger:
  level: "${LOG_LEVEL:debug}"
  disable: ${LOG_DISABLE:false}
discord:
  worker_count: ${DISCORD_WORKER_COUNT:5}
  app_id: "${DISCORD_APP_ID}"
  token: "${DISCORD_TOKEN}"
  shard_id: ${DISCORD_SHARD_ID:0}
  shard_count: ${DISCORD_SHARD_COUNT:1}
lavaLink:
  nodes:
    - name: "main"
      host: "${LAVALINK_MAIN_NODE_HOST:''}"
      port: "${LAVALINK_MAIN_NODE_PORT:2333}"
      password: "${LAVALINK_MAIN_NODE_PASSWORD:password}"
      secure: "${LAVALINK_MAIN_NODE_SECURE:false}"
translator:
  default_locale: "${TRANSLATOR_DEFAULT_LOCALE:en-US}"
  available_locales:
    - "ru"
cache:
  default: "memory"
  stores:
    memory:
      driver: "memory"
      max_items: 1000
service:
  music_player:
    idle_timeout: "${MUSIC_PLAYER_IDLE_TIMEOUT:30m}"