database:
  driver: "${DB_DRIVER:postgres}"
  postgres:
    host: "${DB_POSTGRES_HOST:localhost}"
    port: "${DB_POSTGRES_PORT:5432}"
    user: "${DB_POSTGRES_USER:discord_bot}"
    password: "${DB_POSTGRES_PASSWORD:root}"
    db: "${DB_POSTGRES_DB:discord_bot}"
    sslMode: "${DB_POSTGRES_SSLMODE:disable}"
  sqlite:
    path: "${DB_SQLITE_PATH:./storage/db.sqlite}"
app:
  name: "discord-bot"
  debug: ${APP_DEBUG:false}
  repository: "${APP_REPOSITORY:}"
pprof:
  addr: "${PPROF_ADDR::6060}"
logger:
  level: "${LOG_LEVEL:debug}"
  disable: ${LOG_DISABLE:false}
discord:
  workerCount: ${DISCORD_WORKER_COUNT:5}
  appID: "${DISCORD_APP_ID}"
  token: "${DISCORD_TOKEN}"
  intents:
    - Guilds
    - GuildVoiceStates
    - GuildMessages
    - GuildMessageReactions
lavaLink:
  nodes:
    - name: "main"
      host: "${LAVA_LINK_HOST:''}"
      port: "${LAVA_LINK_PORT:2333}"
      password: "${LAVA_LINK_PASSWORD:password}"
      secure: "${LAVA_LINK_SECURE:false}"
translator:
  defaultLocale: "en-US"
  availableLocales:
    - "ru"
service:
  musicPlayer:
    idleTimeout: "${MUSIC_PLAYER_IDLE_TIMEOUT:30m}"