// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tempvoicechannelstatemock

import (
	"context"
	"uuid"

	"github.com/SkinonikS/discord-bot-go/internal/service/repository/temp_voice_channel_state"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// DeleteManyByIDs provides a mock function for the type MockRepo
func (_mock *MockRepo) DeleteManyByIDs(ctx context.Context, ids []uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManyByIDs")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_DeleteManyByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManyByIDs'
type MockRepo_DeleteManyByIDs_Call struct {
	*mock.Call
}

// DeleteManyByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockRepo_Expecter) DeleteManyByIDs(ctx any, ids any) *MockRepo_DeleteManyByIDs_Call {
	return &MockRepo_DeleteManyByIDs_Call{Call: _e.mock.On("DeleteManyByIDs", ctx, ids)}
}

func (_c *MockRepo_DeleteManyByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockRepo_DeleteManyByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_DeleteManyByIDs_Call) Return(n int64, err error) *MockRepo_DeleteManyByIDs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepo_DeleteManyByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (int64, error)) *MockRepo_DeleteManyByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockRepo
func (_mock *MockRepo) Find(ctx context.Context, params tempvoicechannelstate.FindParams) ([]tempvoicechannelstate.TempVoiceChannelState, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []tempvoicechannelstate.TempVoiceChannelState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tempvoicechannelstate.FindParams) ([]tempvoicechannelstate.TempVoiceChannelState, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, tempvoicechannelstate.FindParams) []tempvoicechannelstate.TempVoiceChannelState); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tempvoicechannelstate.TempVoiceChannelState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, tempvoicechannelstate.FindParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRepo_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - params tempvoicechannelstate.FindParams
func (_e *MockRepo_Expecter) Find(ctx any, params any) *MockRepo_Find_Call {
	return &MockRepo_Find_Call{Call: _e.mock.On("Find", ctx, params)}
}

func (_c *MockRepo_Find_Call) Run(run func(ctx context.Context, params tempvoicechannelstate.FindParams)) *MockRepo_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tempvoicechannelstate.FindParams
		if args[1] != nil {
			arg1 = args[1].(tempvoicechannelstate.FindParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Find_Call) Return(tempVoiceChannelStates []tempvoicechannelstate.TempVoiceChannelState, err error) *MockRepo_Find_Call {
	_c.Call.Return(tempVoiceChannelStates, err)
	return _c
}

func (_c *MockRepo_Find_Call) RunAndReturn(run func(ctx context.Context, params tempvoicechannelstate.FindParams) ([]tempvoicechannelstate.TempVoiceChannelState, error)) *MockRepo_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepo
func (_mock *MockRepo) Save(ctx context.Context, state *tempvoicechannelstate.TempVoiceChannelState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *tempvoicechannelstate.TempVoiceChannelState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - state *tempvoicechannelstate.TempVoiceChannelState
func (_e *MockRepo_Expecter) Save(ctx any, state any) *MockRepo_Save_Call {
	return &MockRepo_Save_Call{Call: _e.mock.On("Save", ctx, state)}
}

func (_c *MockRepo_Save_Call) Run(run func(ctx context.Context, state *tempvoicechannelstate.TempVoiceChannelState)) *MockRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *tempvoicechannelstate.TempVoiceChannelState
		if args[1] != nil {
			arg1 = args[1].(*tempvoicechannelstate.TempVoiceChannelState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Save_Call) Return(err error) *MockRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Save_Call) RunAndReturn(run func(ctx context.Context, state *tempvoicechannelstate.TempVoiceChannelState) error) *MockRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function for the type MockRepo
func (_mock *MockRepo) Transaction(ctx context.Context, fn func(tx tempvoicechannelstate.Repo) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx tempvoicechannelstate.Repo) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockRepo_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx tempvoicechannelstate.Repo) error
func (_e *MockRepo_Expecter) Transaction(ctx any, fn any) *MockRepo_Transaction_Call {
	return &MockRepo_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockRepo_Transaction_Call) Run(run func(ctx context.Context, fn func(tx tempvoicechannelstate.Repo) error)) *MockRepo_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx tempvoicechannelstate.Repo) error
		if args[1] != nil {
			arg1 = args[1].(func(tx tempvoicechannelstate.Repo) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Transaction_Call) Return(err error) *MockRepo_Transaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Transaction_Call) RunAndReturn(run func(ctx context.Context, fn func(tx tempvoicechannelstate.Repo) error) error) *MockRepo_Transaction_Call {
	_c.Call.Return(run)
	return _c
}
