// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package discordmock

import (
	"context"
	"time"

	"github.com/disgoorg/disgo/gateway"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGateway creates a new instance of MockGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGateway {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGateway is an autogenerated mock type for the Gateway type
type MockGateway struct {
	mock.Mock
}

type MockGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGateway) EXPECT() *MockGateway_Expecter {
	return &MockGateway_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockGateway
func (_mock *MockGateway) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockGateway_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGateway_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGateway_Expecter) Close(ctx any) *MockGateway_Close_Call {
	return &MockGateway_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockGateway_Close_Call) Run(run func(ctx context.Context)) *MockGateway_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGateway_Close_Call) Return() *MockGateway_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGateway_Close_Call) RunAndReturn(run func(ctx context.Context)) *MockGateway_Close_Call {
	_c.Run(run)
	return _c
}

// CloseWithCode provides a mock function for the type MockGateway
func (_mock *MockGateway) CloseWithCode(ctx context.Context, code int, message string) {
	_mock.Called(ctx, code, message)
	return
}

// MockGateway_CloseWithCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseWithCode'
type MockGateway_CloseWithCode_Call struct {
	*mock.Call
}

// CloseWithCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code int
//   - message string
func (_e *MockGateway_Expecter) CloseWithCode(ctx any, code any, message any) *MockGateway_CloseWithCode_Call {
	return &MockGateway_CloseWithCode_Call{Call: _e.mock.On("CloseWithCode", ctx, code, message)}
}

func (_c *MockGateway_CloseWithCode_Call) Run(run func(ctx context.Context, code int, message string)) *MockGateway_CloseWithCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGateway_CloseWithCode_Call) Return() *MockGateway_CloseWithCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGateway_CloseWithCode_Call) RunAndReturn(run func(ctx context.Context, code int, message string)) *MockGateway_CloseWithCode_Call {
	_c.Run(run)
	return _c
}

// Intents provides a mock function for the type MockGateway
func (_mock *MockGateway) Intents() gateway.Intents {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Intents")
	}

	var r0 gateway.Intents
	if returnFunc, ok := ret.Get(0).(func() gateway.Intents); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gateway.Intents)
	}
	return r0
}

// MockGateway_Intents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Intents'
type MockGateway_Intents_Call struct {
	*mock.Call
}

// Intents is a helper method to define mock.On call
func (_e *MockGateway_Expecter) Intents() *MockGateway_Intents_Call {
	return &MockGateway_Intents_Call{Call: _e.mock.On("Intents")}
}

func (_c *MockGateway_Intents_Call) Run(run func()) *MockGateway_Intents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_Intents_Call) Return(intents gateway.Intents) *MockGateway_Intents_Call {
	_c.Call.Return(intents)
	return _c
}

func (_c *MockGateway_Intents_Call) RunAndReturn(run func() gateway.Intents) *MockGateway_Intents_Call {
	_c.Call.Return(run)
	return _c
}

// LastSequenceReceived provides a mock function for the type MockGateway
func (_mock *MockGateway) LastSequenceReceived() *int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastSequenceReceived")
	}

	var r0 *int
	if returnFunc, ok := ret.Get(0).(func() *int); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}
	return r0
}

// MockGateway_LastSequenceReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastSequenceReceived'
type MockGateway_LastSequenceReceived_Call struct {
	*mock.Call
}

// LastSequenceReceived is a helper method to define mock.On call
func (_e *MockGateway_Expecter) LastSequenceReceived() *MockGateway_LastSequenceReceived_Call {
	return &MockGateway_LastSequenceReceived_Call{Call: _e.mock.On("LastSequenceReceived")}
}

func (_c *MockGateway_LastSequenceReceived_Call) Run(run func()) *MockGateway_LastSequenceReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_LastSequenceReceived_Call) Return(n *int) *MockGateway_LastSequenceReceived_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockGateway_LastSequenceReceived_Call) RunAndReturn(run func() *int) *MockGateway_LastSequenceReceived_Call {
	_c.Call.Return(run)
	return _c
}

// Latency provides a mock function for the type MockGateway
func (_mock *MockGateway) Latency() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Latency")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockGateway_Latency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Latency'
type MockGateway_Latency_Call struct {
	*mock.Call
}

// Latency is a helper method to define mock.On call
func (_e *MockGateway_Expecter) Latency() *MockGateway_Latency_Call {
	return &MockGateway_Latency_Call{Call: _e.mock.On("Latency")}
}

func (_c *MockGateway_Latency_Call) Run(run func()) *MockGateway_Latency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_Latency_Call) Return(duration time.Duration) *MockGateway_Latency_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockGateway_Latency_Call) RunAndReturn(run func() time.Duration) *MockGateway_Latency_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockGateway
func (_mock *MockGateway) Open(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGateway_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockGateway_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGateway_Expecter) Open(ctx any) *MockGateway_Open_Call {
	return &MockGateway_Open_Call{Call: _e.mock.On("Open", ctx)}
}

func (_c *MockGateway_Open_Call) Run(run func(ctx context.Context)) *MockGateway_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGateway_Open_Call) Return(err error) *MockGateway_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGateway_Open_Call) RunAndReturn(run func(ctx context.Context) error) *MockGateway_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Presence provides a mock function for the type MockGateway
func (_mock *MockGateway) Presence() *gateway.MessageDataPresenceUpdate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Presence")
	}

	var r0 *gateway.MessageDataPresenceUpdate
	if returnFunc, ok := ret.Get(0).(func() *gateway.MessageDataPresenceUpdate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.MessageDataPresenceUpdate)
		}
	}
	return r0
}

// MockGateway_Presence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Presence'
type MockGateway_Presence_Call struct {
	*mock.Call
}

// Presence is a helper method to define mock.On call
func (_e *MockGateway_Expecter) Presence() *MockGateway_Presence_Call {
	return &MockGateway_Presence_Call{Call: _e.mock.On("Presence")}
}

func (_c *MockGateway_Presence_Call) Run(run func()) *MockGateway_Presence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_Presence_Call) Return(messageDataPresenceUpdate *gateway.MessageDataPresenceUpdate) *MockGateway_Presence_Call {
	_c.Call.Return(messageDataPresenceUpdate)
	return _c
}

func (_c *MockGateway_Presence_Call) RunAndReturn(run func() *gateway.MessageDataPresenceUpdate) *MockGateway_Presence_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeURL provides a mock function for the type MockGateway
func (_mock *MockGateway) ResumeURL() *string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResumeURL")
	}

	var r0 *string
	if returnFunc, ok := ret.Get(0).(func() *string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	return r0
}

// MockGateway_ResumeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeURL'
type MockGateway_ResumeURL_Call struct {
	*mock.Call
}

// ResumeURL is a helper method to define mock.On call
func (_e *MockGateway_Expecter) ResumeURL() *MockGateway_ResumeURL_Call {
	return &MockGateway_ResumeURL_Call{Call: _e.mock.On("ResumeURL")}
}

func (_c *MockGateway_ResumeURL_Call) Run(run func()) *MockGateway_ResumeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_ResumeURL_Call) Return(s *string) *MockGateway_ResumeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGateway_ResumeURL_Call) RunAndReturn(run func() *string) *MockGateway_ResumeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockGateway
func (_mock *MockGateway) Send(ctx context.Context, op gateway.Opcode, data gateway.MessageData) error {
	ret := _mock.Called(ctx, op, data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gateway.Opcode, gateway.MessageData) error); ok {
		r0 = returnFunc(ctx, op, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGateway_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockGateway_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - op gateway.Opcode
//   - data gateway.MessageData
func (_e *MockGateway_Expecter) Send(ctx any, op any, data any) *MockGateway_Send_Call {
	return &MockGateway_Send_Call{Call: _e.mock.On("Send", ctx, op, data)}
}

func (_c *MockGateway_Send_Call) Run(run func(ctx context.Context, op gateway.Opcode, data gateway.MessageData)) *MockGateway_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gateway.Opcode
		if args[1] != nil {
			arg1 = args[1].(gateway.Opcode)
		}
		var arg2 gateway.MessageData
		if args[2] != nil {
			arg2 = args[2].(gateway.MessageData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGateway_Send_Call) Return(err error) *MockGateway_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGateway_Send_Call) RunAndReturn(run func(ctx context.Context, op gateway.Opcode, data gateway.MessageData) error) *MockGateway_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SessionID provides a mock function for the type MockGateway
func (_mock *MockGateway) SessionID() *string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SessionID")
	}

	var r0 *string
	if returnFunc, ok := ret.Get(0).(func() *string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	return r0
}

// MockGateway_SessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionID'
type MockGateway_SessionID_Call struct {
	*mock.Call
}

// SessionID is a helper method to define mock.On call
func (_e *MockGateway_Expecter) SessionID() *MockGateway_SessionID_Call {
	return &MockGateway_SessionID_Call{Call: _e.mock.On("SessionID")}
}

func (_c *MockGateway_SessionID_Call) Run(run func()) *MockGateway_SessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_SessionID_Call) Return(s *string) *MockGateway_SessionID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGateway_SessionID_Call) RunAndReturn(run func() *string) *MockGateway_SessionID_Call {
	_c.Call.Return(run)
	return _c
}

// ShardCount provides a mock function for the type MockGateway
func (_mock *MockGateway) ShardCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShardCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockGateway_ShardCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShardCount'
type MockGateway_ShardCount_Call struct {
	*mock.Call
}

// ShardCount is a helper method to define mock.On call
func (_e *MockGateway_Expecter) ShardCount() *MockGateway_ShardCount_Call {
	return &MockGateway_ShardCount_Call{Call: _e.mock.On("ShardCount")}
}

func (_c *MockGateway_ShardCount_Call) Run(run func()) *MockGateway_ShardCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_ShardCount_Call) Return(n int) *MockGateway_ShardCount_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockGateway_ShardCount_Call) RunAndReturn(run func() int) *MockGateway_ShardCount_Call {
	_c.Call.Return(run)
	return _c
}

// ShardID provides a mock function for the type MockGateway
func (_mock *MockGateway) ShardID() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShardID")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockGateway_ShardID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShardID'
type MockGateway_ShardID_Call struct {
	*mock.Call
}

// ShardID is a helper method to define mock.On call
func (_e *MockGateway_Expecter) ShardID() *MockGateway_ShardID_Call {
	return &MockGateway_ShardID_Call{Call: _e.mock.On("ShardID")}
}

func (_c *MockGateway_ShardID_Call) Run(run func()) *MockGateway_ShardID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_ShardID_Call) Return(n int) *MockGateway_ShardID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockGateway_ShardID_Call) RunAndReturn(run func() int) *MockGateway_ShardID_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockGateway
func (_mock *MockGateway) Status() gateway.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 gateway.Status
	if returnFunc, ok := ret.Get(0).(func() gateway.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gateway.Status)
	}
	return r0
}

// MockGateway_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockGateway_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockGateway_Expecter) Status() *MockGateway_Status_Call {
	return &MockGateway_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockGateway_Status_Call) Run(run func()) *MockGateway_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGateway_Status_Call) Return(status gateway.Status) *MockGateway_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *MockGateway_Status_Call) RunAndReturn(run func() gateway.Status) *MockGateway_Status_Call {
	_c.Call.Return(run)
	return _c
}
