// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package guildcommandsettingmock

import (
	"context"

	"github.com/disgoorg/snowflake/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// Disable provides a mock function for the type MockRepo
func (_mock *MockRepo) Disable(ctx context.Context, guildID snowflake.ID, commandName string) error {
	ret := _mock.Called(ctx, guildID, commandName)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID, string) error); ok {
		r0 = returnFunc(ctx, guildID, commandName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type MockRepo_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID snowflake.ID
//   - commandName string
func (_e *MockRepo_Expecter) Disable(ctx any, guildID any, commandName any) *MockRepo_Disable_Call {
	return &MockRepo_Disable_Call{Call: _e.mock.On("Disable", ctx, guildID, commandName)}
}

func (_c *MockRepo_Disable_Call) Run(run func(ctx context.Context, guildID snowflake.ID, commandName string)) *MockRepo_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(snowflake.ID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_Disable_Call) Return(err error) *MockRepo_Disable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Disable_Call) RunAndReturn(run func(ctx context.Context, guildID snowflake.ID, commandName string) error) *MockRepo_Disable_Call {
	_c.Call.Return(run)
	return _c
}

// Enable provides a mock function for the type MockRepo
func (_mock *MockRepo) Enable(ctx context.Context, guildID snowflake.ID, commandName string) error {
	ret := _mock.Called(ctx, guildID, commandName)

	if len(ret) == 0 {
		panic("no return value specified for Enable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID, string) error); ok {
		r0 = returnFunc(ctx, guildID, commandName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockRepo_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID snowflake.ID
//   - commandName string
func (_e *MockRepo_Expecter) Enable(ctx any, guildID any, commandName any) *MockRepo_Enable_Call {
	return &MockRepo_Enable_Call{Call: _e.mock.On("Enable", ctx, guildID, commandName)}
}

func (_c *MockRepo_Enable_Call) Run(run func(ctx context.Context, guildID snowflake.ID, commandName string)) *MockRepo_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(snowflake.ID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_Enable_Call) Return(err error) *MockRepo_Enable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Enable_Call) RunAndReturn(run func(ctx context.Context, guildID snowflake.ID, commandName string) error) *MockRepo_Enable_Call {
	_c.Call.Return(run)
	return _c
}

// IsDisabled provides a mock function for the type MockRepo
func (_mock *MockRepo) IsDisabled(ctx context.Context, guildID snowflake.ID, commandName string) (bool, error) {
	ret := _mock.Called(ctx, guildID, commandName)

	if len(ret) == 0 {
		panic("no return value specified for IsDisabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID, string) (bool, error)); ok {
		return returnFunc(ctx, guildID, commandName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID, string) bool); ok {
		r0 = returnFunc(ctx, guildID, commandName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snowflake.ID, string) error); ok {
		r1 = returnFunc(ctx, guildID, commandName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_IsDisabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDisabled'
type MockRepo_IsDisabled_Call struct {
	*mock.Call
}

// IsDisabled is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID snowflake.ID
//   - commandName string
func (_e *MockRepo_Expecter) IsDisabled(ctx any, guildID any, commandName any) *MockRepo_IsDisabled_Call {
	return &MockRepo_IsDisabled_Call{Call: _e.mock.On("IsDisabled", ctx, guildID, commandName)}
}

func (_c *MockRepo_IsDisabled_Call) Run(run func(ctx context.Context, guildID snowflake.ID, commandName string)) *MockRepo_IsDisabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(snowflake.ID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_IsDisabled_Call) Return(b bool, err error) *MockRepo_IsDisabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepo_IsDisabled_Call) RunAndReturn(run func(ctx context.Context, guildID snowflake.ID, commandName string) (bool, error)) *MockRepo_IsDisabled_Call {
	_c.Call.Return(run)
	return _c
}

// ListDisabledByGuildID provides a mock function for the type MockRepo
func (_mock *MockRepo) ListDisabledByGuildID(ctx context.Context, guildID snowflake.ID) ([]string, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for ListDisabledByGuildID")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID) ([]string, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, snowflake.ID) []string); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, snowflake.ID) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_ListDisabledByGuildID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDisabledByGuildID'
type MockRepo_ListDisabledByGuildID_Call struct {
	*mock.Call
}

// ListDisabledByGuildID is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID snowflake.ID
func (_e *MockRepo_Expecter) ListDisabledByGuildID(ctx any, guildID any) *MockRepo_ListDisabledByGuildID_Call {
	return &MockRepo_ListDisabledByGuildID_Call{Call: _e.mock.On("ListDisabledByGuildID", ctx, guildID)}
}

func (_c *MockRepo_ListDisabledByGuildID_Call) Run(run func(ctx context.Context, guildID snowflake.ID)) *MockRepo_ListDisabledByGuildID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 snowflake.ID
		if args[1] != nil {
			arg1 = args[1].(snowflake.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_ListDisabledByGuildID_Call) Return(strings []string, err error) *MockRepo_ListDisabledByGuildID_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepo_ListDisabledByGuildID_Call) RunAndReturn(run func(ctx context.Context, guildID snowflake.ID) ([]string, error)) *MockRepo_ListDisabledByGuildID_Call {
	_c.Call.Return(run)
	return _c
}
