// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package translatormock

import (
	"github.com/disgoorg/disgo/discord"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// LoadTranslations provides a mock function for the type MockTranslator
func (_mock *MockTranslator) LoadTranslations(locales ...discord.Locale) error {
	var tmpRet mock.Arguments
	if len(locales) > 0 {
		tmpRet = _mock.Called(locales)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LoadTranslations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...discord.Locale) error); ok {
		r0 = returnFunc(locales...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTranslator_LoadTranslations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadTranslations'
type MockTranslator_LoadTranslations_Call struct {
	*mock.Call
}

// LoadTranslations is a helper method to define mock.On call
//   - locales ...discord.Locale
func (_e *MockTranslator_Expecter) LoadTranslations(locales ...any) *MockTranslator_LoadTranslations_Call {
	return &MockTranslator_LoadTranslations_Call{Call: _e.mock.On("LoadTranslations",
		append([]any{}, locales...)...)}
}

func (_c *MockTranslator_LoadTranslations_Call) Run(run func(locales ...discord.Locale)) *MockTranslator_LoadTranslations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []discord.Locale
		var variadicArgs []discord.Locale
		if len(args) > 0 {
			variadicArgs = args[0].([]discord.Locale)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockTranslator_LoadTranslations_Call) Return(err error) *MockTranslator_LoadTranslations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTranslator_LoadTranslations_Call) RunAndReturn(run func(locales ...discord.Locale) error) *MockTranslator_LoadTranslations_Call {
	_c.Call.Return(run)
	return _c
}

// Localize provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Localize(locale discord.Locale, lc *i18n.LocalizeConfig) string {
	ret := _mock.Called(locale, lc)

	if len(ret) == 0 {
		panic("no return value specified for Localize")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(discord.Locale, *i18n.LocalizeConfig) string); ok {
		r0 = returnFunc(locale, lc)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTranslator_Localize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Localize'
type MockTranslator_Localize_Call struct {
	*mock.Call
}

// Localize is a helper method to define mock.On call
//   - locale discord.Locale
//   - lc *i18n.LocalizeConfig
func (_e *MockTranslator_Expecter) Localize(locale any, lc any) *MockTranslator_Localize_Call {
	return &MockTranslator_Localize_Call{Call: _e.mock.On("Localize", locale, lc)}
}

func (_c *MockTranslator_Localize_Call) Run(run func(locale discord.Locale, lc *i18n.LocalizeConfig)) *MockTranslator_Localize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 discord.Locale
		if args[0] != nil {
			arg0 = args[0].(discord.Locale)
		}
		var arg1 *i18n.LocalizeConfig
		if args[1] != nil {
			arg1 = args[1].(*i18n.LocalizeConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTranslator_Localize_Call) Return(s string) *MockTranslator_Localize_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTranslator_Localize_Call) RunAndReturn(run func(locale discord.Locale, lc *i18n.LocalizeConfig) string) *MockTranslator_Localize_Call {
	_c.Call.Return(run)
	return _c
}

// LocalizeAll provides a mock function for the type MockTranslator
func (_mock *MockTranslator) LocalizeAll(lc *i18n.LocalizeConfig) map[discord.Locale]string {
	ret := _mock.Called(lc)

	if len(ret) == 0 {
		panic("no return value specified for LocalizeAll")
	}

	var r0 map[discord.Locale]string
	if returnFunc, ok := ret.Get(0).(func(*i18n.LocalizeConfig) map[discord.Locale]string); ok {
		r0 = returnFunc(lc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[discord.Locale]string)
		}
	}
	return r0
}

// MockTranslator_LocalizeAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalizeAll'
type MockTranslator_LocalizeAll_Call struct {
	*mock.Call
}

// LocalizeAll is a helper method to define mock.On call
//   - lc *i18n.LocalizeConfig
func (_e *MockTranslator_Expecter) LocalizeAll(lc any) *MockTranslator_LocalizeAll_Call {
	return &MockTranslator_LocalizeAll_Call{Call: _e.mock.On("LocalizeAll", lc)}
}

func (_c *MockTranslator_LocalizeAll_Call) Run(run func(lc *i18n.LocalizeConfig)) *MockTranslator_LocalizeAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *i18n.LocalizeConfig
		if args[0] != nil {
			arg0 = args[0].(*i18n.LocalizeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_LocalizeAll_Call) Return(localeToString map[discord.Locale]string) *MockTranslator_LocalizeAll_Call {
	_c.Call.Return(localeToString)
	return _c
}

func (_c *MockTranslator_LocalizeAll_Call) RunAndReturn(run func(lc *i18n.LocalizeConfig) map[discord.Locale]string) *MockTranslator_LocalizeAll_Call {
	_c.Call.Return(run)
	return _c
}

// LocalizeMessage provides a mock function for the type MockTranslator
func (_mock *MockTranslator) LocalizeMessage(locale discord.Locale, msg *i18n.Message) string {
	ret := _mock.Called(locale, msg)

	if len(ret) == 0 {
		panic("no return value specified for LocalizeMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(discord.Locale, *i18n.Message) string); ok {
		r0 = returnFunc(locale, msg)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTranslator_LocalizeMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalizeMessage'
type MockTranslator_LocalizeMessage_Call struct {
	*mock.Call
}

// LocalizeMessage is a helper method to define mock.On call
//   - locale discord.Locale
//   - msg *i18n.Message
func (_e *MockTranslator_Expecter) LocalizeMessage(locale any, msg any) *MockTranslator_LocalizeMessage_Call {
	return &MockTranslator_LocalizeMessage_Call{Call: _e.mock.On("LocalizeMessage", locale, msg)}
}

func (_c *MockTranslator_LocalizeMessage_Call) Run(run func(locale discord.Locale, msg *i18n.Message)) *MockTranslator_LocalizeMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 discord.Locale
		if args[0] != nil {
			arg0 = args[0].(discord.Locale)
		}
		var arg1 *i18n.Message
		if args[1] != nil {
			arg1 = args[1].(*i18n.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTranslator_LocalizeMessage_Call) Return(s string) *MockTranslator_LocalizeMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTranslator_LocalizeMessage_Call) RunAndReturn(run func(locale discord.Locale, msg *i18n.Message) string) *MockTranslator_LocalizeMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SimpleLocalize provides a mock function for the type MockTranslator
func (_mock *MockTranslator) SimpleLocalize(locale discord.Locale, msg string) string {
	ret := _mock.Called(locale, msg)

	if len(ret) == 0 {
		panic("no return value specified for SimpleLocalize")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(discord.Locale, string) string); ok {
		r0 = returnFunc(locale, msg)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTranslator_SimpleLocalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimpleLocalize'
type MockTranslator_SimpleLocalize_Call struct {
	*mock.Call
}

// SimpleLocalize is a helper method to define mock.On call
//   - locale discord.Locale
//   - msg string
func (_e *MockTranslator_Expecter) SimpleLocalize(locale any, msg any) *MockTranslator_SimpleLocalize_Call {
	return &MockTranslator_SimpleLocalize_Call{Call: _e.mock.On("SimpleLocalize", locale, msg)}
}

func (_c *MockTranslator_SimpleLocalize_Call) Run(run func(locale discord.Locale, msg string)) *MockTranslator_SimpleLocalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 discord.Locale
		if args[0] != nil {
			arg0 = args[0].(discord.Locale)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTranslator_SimpleLocalize_Call) Return(s string) *MockTranslator_SimpleLocalize_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTranslator_SimpleLocalize_Call) RunAndReturn(run func(locale discord.Locale, msg string) string) *MockTranslator_SimpleLocalize_Call {
	_c.Call.Return(run)
	return _c
}

// SimpleLocalizeAll provides a mock function for the type MockTranslator
func (_mock *MockTranslator) SimpleLocalizeAll(msg string) map[discord.Locale]string {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for SimpleLocalizeAll")
	}

	var r0 map[discord.Locale]string
	if returnFunc, ok := ret.Get(0).(func(string) map[discord.Locale]string); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[discord.Locale]string)
		}
	}
	return r0
}

// MockTranslator_SimpleLocalizeAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimpleLocalizeAll'
type MockTranslator_SimpleLocalizeAll_Call struct {
	*mock.Call
}

// SimpleLocalizeAll is a helper method to define mock.On call
//   - msg string
func (_e *MockTranslator_Expecter) SimpleLocalizeAll(msg any) *MockTranslator_SimpleLocalizeAll_Call {
	return &MockTranslator_SimpleLocalizeAll_Call{Call: _e.mock.On("SimpleLocalizeAll", msg)}
}

func (_c *MockTranslator_SimpleLocalizeAll_Call) Run(run func(msg string)) *MockTranslator_SimpleLocalizeAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_SimpleLocalizeAll_Call) Return(localeToString map[discord.Locale]string) *MockTranslator_SimpleLocalizeAll_Call {
	_c.Call.Return(localeToString)
	return _c
}

func (_c *MockTranslator_SimpleLocalizeAll_Call) RunAndReturn(run func(msg string) map[discord.Locale]string) *MockTranslator_SimpleLocalizeAll_Call {
	_c.Call.Return(run)
	return _c
}
